# Generated by Django 2.2.3 on 2019-08-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
