# Generated by Django 2.2.3 on 2019-08-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190806_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
